-- Reverses 0000_v2_data_model.sql. Run with `pnpm --filter @team-impact/api db:rollback`.
DROP TABLE IF EXISTS "reports" CASCADE;
DROP TABLE IF EXISTS "moderation_actions" CASCADE;
DROP TABLE IF EXISTS "events_log" CASCADE;
DROP TABLE IF EXISTS "teams" CASCADE;
DROP TABLE IF EXISTS "memberships" CASCADE;
DROP TABLE IF EXISTS "join_requests" CASCADE;
DROP TABLE IF EXISTS "join_codes" CASCADE;
DROP TABLE IF EXISTS "groups" CASCADE;
DROP TABLE IF EXISTS "colleges" CASCADE;
DROP TABLE IF EXISTS "coach_invites" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "device_tokens" CASCADE;
DROP TABLE IF EXISTS "contact_visibility" CASCADE;
DROP TABLE IF EXISTS "consent_records" CASCADE;
DROP TABLE IF EXISTS "children" CASCADE;
DROP TABLE IF EXISTS "blocks" CASCADE;
DROP TABLE IF EXISTS "shortlists" CASCADE;
DROP TABLE IF EXISTS "shortlist_notes" CASCADE;
DROP TABLE IF EXISTS "shortlist_entries" CASCADE;
DROP TABLE IF EXISTS "saved_searches" CASCADE;
DROP TABLE IF EXISTS "orgs" CASCADE;
DROP TABLE IF EXISTS "org_domains" CASCADE;
DROP TABLE IF EXISTS "rsvps" CASCADE;
DROP TABLE IF EXISTS "reactions" CASCADE;
DROP TABLE IF EXISTS "posts" CASCADE;
DROP TABLE IF EXISTS "events" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "media" CASCADE;
DROP TABLE IF EXISTS "ingested_records" CASCADE;
DROP TABLE IF EXISTS "cards" CASCADE;
DROP TYPE IF EXISTS "public"."card_status";
DROP TYPE IF EXISTS "public"."channel_preference";
DROP TYPE IF EXISTS "public"."contact_channel";
DROP TYPE IF EXISTS "public"."contact_scope";
DROP TYPE IF EXISTS "public"."device_platform";
DROP TYPE IF EXISTS "public"."group_kind";
DROP TYPE IF EXISTS "public"."group_visibility";
DROP TYPE IF EXISTS "public"."ingested_status";
DROP TYPE IF EXISTS "public"."join_request_status";
DROP TYPE IF EXISTS "public"."media_kind";
DROP TYPE IF EXISTS "public"."membership_role";
DROP TYPE IF EXISTS "public"."membership_source";
DROP TYPE IF EXISTS "public"."moderation_action";
DROP TYPE IF EXISTS "public"."moderation_status";
DROP TYPE IF EXISTS "public"."org_status";
DROP TYPE IF EXISTS "public"."org_tier";
DROP TYPE IF EXISTS "public"."parse_status";
DROP TYPE IF EXISTS "public"."post_type";
DROP TYPE IF EXISTS "public"."post_visibility";
DROP TYPE IF EXISTS "public"."reaction_kind";
DROP TYPE IF EXISTS "public"."report_severity";
DROP TYPE IF EXISTS "public"."report_state";
DROP TYPE IF EXISTS "public"."rsvp_state";
DROP TYPE IF EXISTS "public"."shortlist_entry_status";
DROP TYPE IF EXISTS "public"."target_type";
DROP TYPE IF EXISTS "public"."team_gender";
DROP TYPE IF EXISTS "public"."team_status";
DROP TYPE IF EXISTS "public"."user_status";
DROP TYPE IF EXISTS "public"."user_type";
