import { colors } from './colors';
import { layout } from './layout';
import { duration, easing, spring, tilt } from './motion';
import { radius } from './radius';
import { spacing } from './spacing';
import { typography, fontFamily, type TypeStyle } from './typography';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const bezier = (b: readonly number[]) => `cubic-bezier(${b.join(', ')})`;

type Vars = [name: string, value: string][];

function flatten(prefix: string, obj: Record<string, unknown>, fmt: (v: unknown) => string): Vars {
  return Object.entries(obj).flatMap(([k, v]) =>
    v !== null && typeof v === 'object'
      ? flatten(`${prefix}-${kebab(k)}`, v as Record<string, unknown>, fmt)
      : [[`${prefix}-${kebab(k)}`, fmt(v)] as [string, string]],
  );
}

const px = (v: unknown) => (v === 0 ? '0' : `${v}px`);
const ms = (v: unknown) => `${v}ms`;
const str = (v: unknown) => String(v);

/** Renders every token as a CSS custom property block. Generated into `tokens.css`. */
export function tokensToCss(): string {
  const vars: Vars = [
    ...flatten('--ti-color', colors, str).filter(([n]) => n !== '--ti-color-team'),
    ['--ti-color-team', 'var(--ti-color-brand)'],
    ...flatten('--ti-space', spacing, px),
    ...flatten('--ti-radius', radius, px),
    ...flatten('--ti-size', layout, px),
    ['--ti-font-display', `'${fontFamily.display}', 'Arial Narrow', sans-serif`],
    ['--ti-font-ui', `'${fontFamily.ui}', system-ui, sans-serif`],
    ...flatten('--ti-duration', duration, ms),
    ...Object.entries(easing).map(([k, v]): [string, string] => [
      `--ti-ease-${kebab(k)}`,
      bezier(v),
    ]),
    ['--ti-spring-stiffness', String(spring.stiffness)],
    ['--ti-spring-damping', String(spring.damping)],
    ['--ti-spring-mass', String(spring.mass)],
    ['--ti-tilt-max', `${tilt.maxDegrees}deg`],
  ];
  // Type styles as individual properties, so CSS can compose them without a utility layer.
  const type: Vars = [];
  const add = (name: string, t: TypeStyle) => {
    type.push(
      [`--ti-type-${name}-size`, px(t.fontSize)],
      [`--ti-type-${name}-line`, px(t.lineHeight)],
      [`--ti-type-${name}-weight`, String(t.fontWeight)],
      [`--ti-type-${name}-tracking`, `${t.letterSpacing}em`],
    );
  };
  for (const [k, t] of Object.entries(typography.display)) add(`display-${k}`, t);
  add('body', typography.body);
  add('small', typography.small);
  add('caption', typography.caption);
  add('eyebrow', typography.eyebrow);

  const body = [...vars, ...type].map(([n, v]) => `  ${n}: ${v};`).join('\n');
  return [
    '/* GENERATED by `pnpm --filter @team-impact/ui-tokens build:css` from src/*.ts. Do not edit. */',
    `:root {\n${body}\n}`,
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    '    --ti-tilt-max: 0deg;',
    '  }',
    '}',
    '',
  ].join('\n');
}
