// Static reference data for the seed. College names are real; every person is generated by Faker.

export const SEASONS = ['2023-24', '2024-25', '2025-26'] as const;
export const CURRENT_SEASON = SEASONS[SEASONS.length - 1];

export const COLLEGES: { name: string; region: string; city: string; division: string }[] = [
  { name: 'Tufts University', region: 'New England', city: 'Medford', division: 'D3' },
  { name: 'Northeastern University', region: 'New England', city: 'Boston', division: 'D1' },
  { name: 'Boston University', region: 'New England', city: 'Boston', division: 'D1' },
  { name: 'Boston College', region: 'New England', city: 'Chestnut Hill', division: 'D1' },
  { name: 'MIT', region: 'New England', city: 'Cambridge', division: 'D3' },
  { name: 'Harvard University', region: 'New England', city: 'Cambridge', division: 'D1' },
  { name: 'Brandeis University', region: 'New England', city: 'Waltham', division: 'D3' },
  { name: 'Williams College', region: 'New England', city: 'Williamstown', division: 'D3' },
  { name: 'Amherst College', region: 'New England', city: 'Amherst', division: 'D3' },
  { name: 'Bowdoin College', region: 'New England', city: 'Brunswick', division: 'D3' },
  { name: 'Middlebury College', region: 'New England', city: 'Middlebury', division: 'D3' },
  { name: 'University of Connecticut', region: 'New England', city: 'Storrs', division: 'D1' },
  { name: 'UMass Amherst', region: 'New England', city: 'Amherst', division: 'D1' },
  { name: 'Providence College', region: 'New England', city: 'Providence', division: 'D1' },
  { name: 'Brown University', region: 'New England', city: 'Providence', division: 'D1' },
  { name: 'Yale University', region: 'New England', city: 'New Haven', division: 'D1' },
  { name: 'Dartmouth College', region: 'New England', city: 'Hanover', division: 'D1' },
  { name: 'Bentley University', region: 'New England', city: 'Waltham', division: 'D2' },
  { name: 'Wesleyan University', region: 'New England', city: 'Middletown', division: 'D3' },
  { name: 'Babson College', region: 'New England', city: 'Wellesley', division: 'D3' },
  { name: 'Springfield College', region: 'New England', city: 'Springfield', division: 'D3' },
  { name: 'Merrimack College', region: 'New England', city: 'North Andover', division: 'D1' },
  { name: 'Assumption University', region: 'New England', city: 'Worcester', division: 'D2' },
  { name: 'Johns Hopkins University', region: 'Mid-Atlantic', city: 'Baltimore', division: 'D3' },
  { name: 'Georgetown University', region: 'Mid-Atlantic', city: 'Washington', division: 'D1' },
  { name: 'Penn State University', region: 'Mid-Atlantic', city: 'State College', division: 'D1' },
  { name: 'University of Michigan', region: 'Midwest', city: 'Ann Arbor', division: 'D1' },
  { name: 'Northwestern University', region: 'Midwest', city: 'Evanston', division: 'D1' },
  { name: 'Emory University', region: 'Southeast', city: 'Atlanta', division: 'D3' },
  { name: 'Stanford University', region: 'West', city: 'Stanford', division: 'D1' },
];

// Team colours a staff member could save: each reaches 4.5:1 against white or ink text.
export const TEAM_COLORS = [
  '#1E3F7B',
  '#8C1D40',
  '#00563F',
  '#4B2E83',
  '#C8102E',
  '#002E6D',
  '#E87722',
];

export const SPORTS: Record<string, string[]> = {
  Soccer: ['Forward', 'Midfielder', 'Defender', 'Goalkeeper'],
  Basketball: ['Guard', 'Forward', 'Center'],
  Lacrosse: ['Attack', 'Midfield', 'Defense', 'Goalie'],
  'Track & Field': ['Sprints', 'Distance', 'Jumps', 'Throws'],
  Swimming: ['Freestyle', 'Backstroke', 'Breaststroke', 'Butterfly'],
  Volleyball: ['Setter', 'Outside Hitter', 'Libero', 'Middle Blocker'],
  Rowing: ['Port', 'Starboard', 'Coxswain'],
  'Ice Hockey': ['Forward', 'Defense', 'Goalie'],
  'Field Hockey': ['Forward', 'Midfield', 'Back', 'Goalkeeper'],
  Tennis: ['Singles', 'Doubles'],
};

export const MAJORS = [
  'Computer Science',
  'Economics',
  'Biology',
  'Psychology',
  'Mechanical Engineering',
  'International Relations',
  'Business Administration',
  'English',
  'Political Science',
  'Data Science',
  'Communications',
  'Mathematics',
  'Kinesiology',
  'Environmental Studies',
];

export const INDUSTRIES = [
  'Finance',
  'Technology',
  'Consulting',
  'Education',
  'Media',
  'Real Estate',
  'Nonprofit',
  'Sports Management',
  'Law',
  'Marketing',
];

export const AFFINITY_GROUPS = [
  'Women in STEM Athletes',
  'LGBTQ+ Athletes & Allies',
  'Black Student-Athletes Network',
  'Latinx Athletes',
  'International Athletes',
  'Athletes in Finance',
  'Faith & Sport',
];

export const POST_TEMPLATES = [
  'Great win today against {team}! Proud of everyone who showed up.',
  'Early lift tomorrow at 6am. Who is in?',
  'Huge thanks to our families for coming out this weekend.',
  'Film session moved to Thursday, same room.',
  'Anyone have notes from the nutrition workshop?',
  'Recovery day. Ice baths are undefeated.',
  'Senior night is coming up, let us make it loud.',
  'Just finished my internship application, fingers crossed.',
  'Who wants to carpool to the away game on Saturday?',
  'Shoutout to {name} for the clutch play in the second half.',
  'Practice is outdoors tomorrow, bring layers.',
  'Volunteering at the youth clinic Sunday morning if anyone wants to join.',
  'New PR in the weight room today!',
  'Study hall is packed this week, midterms are real.',
  'Looking for mentors in {industry}, any alumni around?',
  'Bus leaves at 7:15 sharp. Do not be late.',
];

export const COMMENT_TEMPLATES = [
  'Let us go!',
  'So proud of this team.',
  'Count me in.',
  'Great work everyone.',
  'See you there!',
  'This is awesome.',
  'Thanks for sharing.',
  'Happy to help, message me.',
  'Huge.',
  'Could not agree more.',
];

/**
 * Deliberately awful posts for the moderation classifier (TI-42). All seeded `pending`, so none of
 * them would ever appear in a feed. Names, numbers and links are fake.
 */
export const AWFUL_POSTS: { text: string; category: string }[] = [
  {
    category: 'spam',
    text: 'Make $5,000 a week from your dorm!!! DM me or click bit.ly/not-a-scam',
  },
  { category: 'spam', text: 'Free followers!!! Free followers!!! Free followers!!! spam.example' },
  {
    category: 'harassment',
    text: 'Honestly you are the worst player I have ever seen. Quit the team, nobody wants you here.',
  },
  { category: 'harassment', text: 'u r so ugly lol delete ur account' },
  {
    category: 'threat',
    text: 'If we lose Saturday I know where some of you park. Just saying.',
  },
  {
    category: 'doxxing',
    text: "Here is the ref's home address and number, go tell him what you think: 12 Fake St, 555-0100",
  },
  {
    category: 'hate',
    text: 'People from that school are all trash and do not belong in this sport.',
  },
  {
    category: 'contraband',
    text: 'Selling game-day supplements that are definitely not banned. Cash only, discreet shipping.',
  },
  {
    category: 'child_safety',
    text: 'Anyone under 16 on this team want easy money? Message me privately and do not tell your parents.',
  },
  {
    category: 'self_harm',
    text: 'I am going to hurt myself after this season, nobody would even notice.',
  },
];
